
language: node_js
node_js:
    - "6"

cache: yarn

before_install:
    - openssl aes-256-cbc -K $encrypted_a62952c62272_key -iv $encrypted_a62952c62272_iv -in deploy_key.pem.enc -out deploy_key.pem -d

script:
    - gulp build
    - gulp assets
    - gulp php
    - gulp sitemap

after_success:
    - node_modules/.bin/gh-pages-travis
    
env:
    global:
        - DEPLOY_BRANCH="master"
        - SOURCE_DIR="build"
        - TARGET_BRANCH="deploy"
        - SSH_KEY="deploy_key.pem"
        - GIT_NAME="travis"
        - GIT_EMAIL="deploy@travis-ci.org"