version: '2'

services:    
    # nginx-proxy:
    #     image: jwilder/nginx-proxy
    #     container_name: nginx-proxy
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         - /var/run/docker.sock:/tmp/docker.sock:ro
    #         - /certs:/etc/nginx/certs
    #         - /etc/nginx/vhost.d
    #         - /usr/share/nginx/html
    # 
    # nginx-letsencrypt:
    #     image: jrcs/letsencrypt-nginx-proxy-companion
    #     container_name: nginx-letsencrypt
    #     volumes:
    #         - /var/run/docker.sock:/tmp/docker.sock:rw
    #         - /var/run/docker.sock:/var/run/docker.sock:ro
    #     volumes_from:
    #         - nginx-proxy
    #     

    kdoveton_web:
        image: nginx:latest
        expose:
            - 80
            - 443
        volumes:
            - ./public:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        environment:
            - "VIRTUAL_HOST=dev.kdoveton.com"
            - "LETSENCRYPT_HOST=dev.kdoveton.com"
            - "LETSENCRYPT_EMAIL=kevindoveton@me.com"
            
    kdoveton_php:
        image: php:fpm
        volumes:
            - ./public:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge